# Nama workflow
name: Build and Deploy to Docker Hub

# Pemicu workflow
on:
  push:
    branches: [ "main" ] # Jalankan saat ada push ke branch 'main'
  workflow_dispatch: # Memungkinkan untuk dijalankan manual

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Mengambil kode dari repository Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Menyiapkan QEMU untuk emulasi arsitektur (WAJIB untuk multi-arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Menyiapkan Docker Buildx, alat untuk build multi-arch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Login ke Docker Hub menggunakan secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Proses build dan push multi-architecture
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # INI BAGIAN PENTING: Tentukan target platform
          platforms: linux/amd64,linux/arm64
          push: true
          # GANTI 'ilham111/uas-pkpl-2206020' JIKA NAMA IMAGE BERBEDA
          tags: ilham111/uas-pkpl-2206020:latest
