# Nama workflow
name: Build and Deploy to Docker Hub

# Kapan workflow ini dijalankan
on:
  push:
    branches:
      - main  # Ganti ini jika branch utama Anda bukan 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Jalankan di lingkungan Linux terbaru

    steps:
      # Langkah 1: Checkout kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3: Build dan push image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .         # Konteks build adalah root direktori
          push: true         # 'true' untuk langsung push ke Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uas-pkpl-2206020:latest # GANTI DENGAN NAMA IMAGE ANDA
          
          # BAGIAN PALING PENTING: Meneruskan secrets sebagai argumen ke Docker build
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}
            # Tambahkan baris lain di sini jika ada secret tambahan
